import java.io.File;
import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.File;

public class DukeSaveLoad {
    private final String SAVE_FILE_NAME = "SavedData.txt";
    private final File saveFile;

    public DukeSaveLoad () {
        this.saveFile = new File(System.getProperty("user.dir") + "/" + SAVE_FILE_NAME);

        try{
            if(!saveFile.exists()) {
                saveFile.createNewFile();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Writes to SaveFile.txt the list data
    public void writeTaskListToSaveFile(TaskList tasks) {
        try {
            String taskListSaveFileString = tasks.toSaveFileString();
            BufferedWriter bw = new BufferedWriter(new FileWriter(saveFile));
            bw.write(tasks.toSaveFileString());
            bw.flush();
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Creates and returns a TaskList generated by reading SaveFile.txt
    public TaskList createTaskListByReadingFromSaveFile () {
        TaskList newTaskList = new TaskList();
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(saveFile));
            //String line = br.readLine();
            String line;

            while((line = br.readLine())!= null) {
                newTaskList.add(Task.createTaskFromSaveFileString(line));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return newTaskList;
    }
}
