import java.io.FileNotFoundException;

public class Duke {

    private Storage storage;
    private TaskList tasks;
    private Ui ui;

    /**
     * Creates an instance of Duke with a path to task list file.
     * New instance of Storage is created to load data from the file and
     * the tasks are stored into a TaskList. New Ui instance is created.
     * If file is not found or empty, exception is reported.
     *
     * @param filePath Path to the file in which list of tasks are stored.
     */
    public Duke(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.load());
        } catch (DukeException e) {
            tasks = new TaskList();
        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        }
    }

    /**
     * Creates new instance of Parser and run parse method to read user input.
     * Greeting message is generated by the Ui.
     */
    public void run() {
        ui.greet();
        Parser p = new Parser(storage, tasks, ui);
        p.parse();
    }

    /**
     * Creates a new instance of Duke with a path to task list file and calls the run method.
     */
    public static void main(String[] args) {
        new Duke("../data/duke.txt").run();
    }
}
