// This is a very general class = about exceptions generated by Duke.
// Raise this exception only when no other better exceptions to choose from.
public class DukeException extends Exception {
    public DukeException(String message) {
        super(message);
    }
}

// This exception is used only when the input keyword is invalid.
class InvalidKeywordException extends DukeException {
    public InvalidKeywordException(String message) {
        super(message);
    }
}

// This exception is used mainly by checked exceptions happened in todo command.
class TodoException extends DukeException {
    public TodoException(String message) {
        super(message);
    }
}

// This exception is used when Todo task is not specified.
class TodoNotSpecifiedException extends TodoException {
    public TodoNotSpecifiedException(String message) {
        super(message);
    }
}

// This exception is used mainly by checked exceptions happened in deadline command.
class DeadlineException extends DukeException {
    public DeadlineException(String message) {
        super(message);
    }
}

// This exception is used when deadline task name is not specified
class DeadlineNameException extends DeadlineException {
    public DeadlineNameException(String message) {
        super(message);
    }
}

// This exception is used when deadline task dead time is not specified
class DeadlineTimeException extends DeadlineException {
    public DeadlineTimeException(String message) {
        super(message);
    }
}

// This exception is used mainly by checked exceptions happened in event command.
class EventException extends DukeException {
    public EventException(String message) {
        super(message);
    }
}

// This exception is used when event task name is not specified
class EventNameException extends EventException {
    public EventNameException(String message) {
        super(message);
    }
}

// This exception is used when event task dead time is not specified
class EventTimeException extends EventException {
    public EventTimeException(String message) {
        super(message);
    }
}
