package duke;

// This is a very general class = about exceptions generated by duke.Duke.
// Raise this exception only when no other better exceptions to choose from.
public class DukeException extends Exception {
    public DukeException(String message) {
        super(message);
    }
}
